
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: grooveguess
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guessYourGroove
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: