spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/grooveguess
    username: postgres
    password: guessYourGroove
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect